server:
  port: 1111

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

#security:
#  basic:
#    enabled: false
#  user:
#    name: test
#    password: 123456